### ISSUE TITLE
localdev init issue

### ISSUE THREAD

**Issue by alinecrsouza** [CoderDojo/cp-local-development#48]
Hello,

I am having a problem when running the `./localdev.js init zen` command.

The log file is attached
[npm-debug.zip](https://github.com/CoderDojo/cp-local-development/files/453428/npm-debug.zip)
. 

Can someone help me?

**Comment by Wardormeur** [comment]
Our support for node 5.7 is not .. official. Try 0.10.49 instead :)

**Comment by alinecrsouza** [comment]
Ok, I'll try.

**Comment by alinecrsouza** [comment]
I could not install this version. The return of the `nvm ls-remote` command is inside the txt file. Can I install the 0.10.46 instead?
[file.txt](https://github.com/CoderDojo/cp-local-development/files/475879/file.txt)

**Comment by Wardormeur** [comment]
Sure !

**Comment by alinecrsouza** [comment]
Hello,
I am having a hard time to make this works. Now I think that another problem occurs. Please take a look at the log. 
PS: I am not a linux user. Maybe it is a silly mistake. I am using a virtual machine only for this, and I tried to follow these steps several times.
[npm-debug.log.zip](https://github.com/CoderDojo/cp-local-development/files/514940/npm-debug.log.zip)

**Comment by Wardormeur** [comment]
Try to run all the scripts from the VM outside out the dropbox directory, it may try to sync at the same time and mess up w/ npm
Weird issue tho :)

**Comment by alinecrsouza** [comment]
Hello, 

After a long break (sorry, I needed to take a break to focus on my master thesis), I finally was able to fix this. Actually, I threw away my VM  and installed a fresh dual boot ubuntu installation. 

Now I have passed this point. I faced some issues with the the test data. I'm not sure if all data were created, but I'll keep going. 

Thank you! And sorry for the delay.
